//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceHome.ServiceHomeDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class FEEDBACK
    {
        public int FEEDBACK_ID { get; set; }
        public string CONTENT { get; set; }
        public Nullable<int> STAFFID { get; set; }
        public Nullable<int> USERID { get; set; }
    }
}
