//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceHome.ServiceHomeDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class OPERATION_LOG
    {
        public int LOG_ID { get; set; }
        public string TYPE { get; set; }
        public string CONTENT { get; set; }
        public Nullable<System.DateTime> CT { get; set; }
        public string APPID { get; set; }
        public string IP { get; set; }
        public string LOGTITLE { get; set; }
    }
}
