//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceHome.ServiceHomeDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class SERVICE_PROPERTY_HEADER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SERVICE_PROPERTY_HEADER()
        {
            this.RATE_PLAN = new HashSet<RATE_PLAN>();
            this.SERVICE_PROPERTY_ITEM = new HashSet<SERVICE_PROPERTY_ITEM>();
        }
    
        public int PROPERTY_HEADER_ID { get; set; }
        public string PROPERTY_HEADER_NAME { get; set; }
        public Nullable<System.DateTime> CREATE_TIME { get; set; }
        public string PROPERTY_HEADER_DESC { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RATE_PLAN> RATE_PLAN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SERVICE_PROPERTY_ITEM> SERVICE_PROPERTY_ITEM { get; set; }
    }
}
