//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceHome.ServiceHomeDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class SERVICE_PROPERTY_ITEM
    {
        public Nullable<int> PROPERTY_ITEM_ID { get; set; }
        public int SERVICE_PROPERTY_ID { get; set; }
        public Nullable<int> PROPERTY_HEADER_ID { get; set; }
    
        public virtual PROPERTY PROPERTY { get; set; }
        public virtual SERVICE_PROPERTY_HEADER SERVICE_PROPERTY_HEADER { get; set; }
    }
}
