//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceHome.ServiceHomeDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class STAFF
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public STAFF()
        {
            this.ORDERS = new HashSet<ORDERS>();
            this.SALRY = new HashSet<SALRY>();
            this.WORKOFF = new HashSet<WORKOFF>();
        }
    
        public int STAFFID { get; set; }
        public string STAFFNAME { get; set; }
        public string PASSWORD { get; set; }
        public string ADDR { get; set; }
        public string EMAIL { get; set; }
        public string PHONE { get; set; }
        public Nullable<System.DateTime> CT { get; set; }
        public Nullable<System.DateTime> LASTUPDATETIME { get; set; }
        public string IDCARD { get; set; }
        public byte[] URL { get; set; }
        public int SEX { get; set; }
        public string QQ { get; set; }
        public int STATE { get; set; }
        public string LASTIP { get; set; }
        public Nullable<System.DateTime> LASTACTION { get; set; }
        public Nullable<int> STAFF_LEVEL { get; set; }
        public Nullable<int> RECENT_CITYID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ORDERS> ORDERS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SALRY> SALRY { get; set; }
        public virtual STAFF_LEVEL STAFF_LEVEL1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WORKOFF> WORKOFF { get; set; }
    }
}
