//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceHome.ServiceHomeDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class USER_PLACES
    {
        public decimal USER_PLACES_ID { get; set; }
        public string PLACE_NAME { get; set; }
        public string ADDRESS { get; set; }
        public string CITYID { get; set; }
        public decimal LNG { get; set; }
        public decimal LAT { get; set; }
    }
}
