//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceHome.ServiceHomeDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class CITY
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CITY()
        {
            this.CITY_SERVICE = new HashSet<CITY_SERVICE>();
            this.COMPANY_CHILD = new HashSet<COMPANY_CHILD>();
            this.RATE_PLAN = new HashSet<RATE_PLAN>();
        }
    
        public int CITYID { get; set; }
        public Nullable<int> PROVINCEID { get; set; }
        public string CITYNAME { get; set; }
        public Nullable<System.DateTime> CT { get; set; }
        public bool ISOPEN { get; set; }
        public string CITYCODE { get; set; }
    
        public virtual PROVICE PROVICE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CITY_SERVICE> CITY_SERVICE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<COMPANY_CHILD> COMPANY_CHILD { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RATE_PLAN> RATE_PLAN { get; set; }
    }
}
