//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceHome.ServiceHomeDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class CITY
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CITY()
        {
            this.COMMISION_RULE = new HashSet<COMMISION_RULE>();
            this.COMPANY_CHILD = new HashSet<COMPANY_CHILD>();
            this.PROVINCE_BASIC_SERVICE = new HashSet<PROVINCE_BASIC_SERVICE>();
        }
    
        public int CITYID { get; set; }
        public Nullable<int> PROVINCEID { get; set; }
        public string CITYNAME { get; set; }
        public Nullable<System.DateTime> CT { get; set; }
        public bool ISOPEN { get; set; }
    
        public virtual PROVICE PROVICE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<COMMISION_RULE> COMMISION_RULE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<COMPANY_CHILD> COMPANY_CHILD { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PROVINCE_BASIC_SERVICE> PROVINCE_BASIC_SERVICE { get; set; }
    }
}
