//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceHome.ServiceHomeDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class COMMISION_RULE_ITEM
    {
        public int RULE_ITEM_ID { get; set; }
        public Nullable<int> SERVICEID { get; set; }
        public Nullable<int> RULE_ID { get; set; }
        public Nullable<decimal> RULE_RATE { get; set; }
        public Nullable<System.DateTime> CT { get; set; }
        public Nullable<System.DateTime> UPDATE_TIME { get; set; }
        public byte[] US_ID { get; set; }
        public byte[] CU_ID { get; set; }
    
        public virtual COMMISION_RULE COMMISION_RULE { get; set; }
        public virtual SERVICE_ITEM SERVICE_ITEM { get; set; }
    }
}
