//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceHome.ServiceHomeDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class COMPANY_CHILD
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public COMPANY_CHILD()
        {
            this.COMPANY_DETAIL_ITEM = new HashSet<COMPANY_DETAIL_ITEM>();
        }
    
        public int CHILD_ID { get; set; }
        public Nullable<int> CITYID { get; set; }
        public string CHILD_NAME { get; set; }
        public int CHILD_MANAGER { get; set; }
    
        public virtual CITY CITY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<COMPANY_DETAIL_ITEM> COMPANY_DETAIL_ITEM { get; set; }
    }
}
