//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceHome.ServiceHomeDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class COMPANY_DETAIL_ITEM
    {
        public int ITEM_ID { get; set; }
        public Nullable<int> CHILD_ID { get; set; }
        public string DETAIL_CODE { get; set; }
        public string CODE { get; set; }
        public string DETAIL { get; set; }
    
        public virtual COMPANY_CHILD COMPANY_CHILD { get; set; }
        public virtual DETAIL_ITEM DETAIL_ITEM { get; set; }
    }
}
