//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceHome.ServiceHomeDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class COUPON_INFO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public COUPON_INFO()
        {
            this.COUPON_RECORD = new HashSet<COUPON_RECORD>();
        }
    
        public int COUPON_ID { get; set; }
        public Nullable<int> CITY_SERVICE_ID { get; set; }
        public string COUPON_NAME { get; set; }
        public byte[] SUMMARY { get; set; }
        public byte[] PIC { get; set; }
        public string PROVISION { get; set; }
        public int DOWNLOADS { get; set; }
        public bool DOWNLOAD_FLAG { get; set; }
        public System.DateTime START_TIME { get; set; }
        public System.DateTime END_TIME { get; set; }
        public System.DateTime SUBMIT_TIME { get; set; }
        public Nullable<System.DateTime> ISSUE_TIME { get; set; }
    
        public virtual PROVINCE_BASIC_SERVICE PROVINCE_BASIC_SERVICE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<COUPON_RECORD> COUPON_RECORD { get; set; }
    }
}
