//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceHome.ServiceHomeDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class MASTERS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MASTERS()
        {
            this.AUTHORMODULES = new HashSet<AUTHORMODULES>();
            this.MEMBERSHIP_PACKAGE = new HashSet<MEMBERSHIP_PACKAGE>();
        }
    
        public int MASTER_ID { get; set; }
        public string PASSWORD { get; set; }
        public string MASTER_NAME { get; set; }
        public string PHONE { get; set; }
        public string EMAIL { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AUTHORMODULES> AUTHORMODULES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MEMBERSHIP_PACKAGE> MEMBERSHIP_PACKAGE { get; set; }
    }
}
