//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceHome.ServiceHomeDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class MEMBERSHIP_PACKAGE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MEMBERSHIP_PACKAGE()
        {
            this.RECHARGE = new HashSet<RECHARGE>();
        }
    
        public int MEM_PACK_ID { get; set; }
        public string PACK_NAME { get; set; }
        public Nullable<System.DateTime> CT { get; set; }
        public Nullable<bool> ISOPEN { get; set; }
        public Nullable<int> CU_ID { get; set; }
        public Nullable<int> PACK_TYPE_ID { get; set; }
        public string REMARK { get; set; }
    
        public virtual MASTERS MASTERS { get; set; }
        public virtual PACK_TYPE PACK_TYPE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RECHARGE> RECHARGE { get; set; }
    }
}
