//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceHome.ServiceHomeDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class ORDER_ITEM
    {
        public int ORDER_DETAIL_ID { get; set; }
        public Nullable<int> ORDERID { get; set; }
        public Nullable<int> RATEPLAN_ID { get; set; }
        public Nullable<System.DateTime> CT { get; set; }
        public Nullable<int> QUANTITY { get; set; }
    
        public virtual ORDERS ORDERS { get; set; }
        public virtual RATEPLAN RATEPLAN { get; set; }
    }
}
