//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceHome.ServiceHomeDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class PACK_TYPE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PACK_TYPE()
        {
            this.MEMBERSHIP_PACKAGE = new HashSet<MEMBERSHIP_PACKAGE>();
        }
    
        public int PACK_TYPE_ID { get; set; }
        public string PACK_TYPE_NAME { get; set; }
        public string PACK_TYPE_CODE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MEMBERSHIP_PACKAGE> MEMBERSHIP_PACKAGE { get; set; }
    }
}
