//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceHome.ServiceHomeDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROPERTY
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PROPERTY()
        {
            this.SERVICE_PROPERTY_ITEM = new HashSet<SERVICE_PROPERTY_ITEM>();
        }
    
        public int PROPERTY_ID { get; set; }
        public string PROPERTY_NAME { get; set; }
        public Nullable<System.DateTime> CREATE_TIME { get; set; }
        public string PROPERTY_DESC { get; set; }
        public string PIC_URL { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SERVICE_PROPERTY_ITEM> SERVICE_PROPERTY_ITEM { get; set; }
    }
}
