//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceHome.ServiceHomeDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROVINCE_BASIC_SERVICE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PROVINCE_BASIC_SERVICE()
        {
            this.COUPON_INFO = new HashSet<COUPON_INFO>();
            this.COUPON_RECORD = new HashSet<COUPON_RECORD>();
            this.RATEPLAN = new HashSet<RATEPLAN>();
            this.REBACK_ITEM = new HashSet<REBACK_ITEM>();
            this.SELFSERVICE = new HashSet<SELFSERVICE>();
        }
    
        public int CITY_SERVICE_ID { get; set; }
        public Nullable<int> SERVICE_ITEM_ID { get; set; }
        public Nullable<int> CITYID { get; set; }
        public Nullable<bool> ISOPEN { get; set; }
        public Nullable<System.DateTime> CT { get; set; }
        public decimal SERVICECOST { get; set; }
        public Nullable<int> CUID { get; set; }
    
        public virtual CITY CITY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<COUPON_INFO> COUPON_INFO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<COUPON_RECORD> COUPON_RECORD { get; set; }
        public virtual SERVICE_ITEM SERVICE_ITEM { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RATEPLAN> RATEPLAN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<REBACK_ITEM> REBACK_ITEM { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SELFSERVICE> SELFSERVICE { get; set; }
    }
}
