//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceHome.ServiceHomeDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class RATE_PLAN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RATE_PLAN()
        {
            this.ORDER_ITEM = new HashSet<ORDER_ITEM>();
        }
    
        public int RATE_PLAN_ID { get; set; }
        public Nullable<int> SERVICE_PLAN_ID { get; set; }
        public Nullable<int> CITYID { get; set; }
        public Nullable<int> PROPERTY_HEADER_ID { get; set; }
        public Nullable<decimal> UNIT_COST { get; set; }
        public string UNIT_NAME { get; set; }
        public Nullable<decimal> ONE_COST { get; set; }
        public string COST_TYPE { get; set; }
        public System.DateTime BEGIN_TIME { get; set; }
        public Nullable<System.DateTime> END_TIME { get; set; }
        public bool IS_OUTDATE { get; set; }
    
        public virtual CITY CITY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ORDER_ITEM> ORDER_ITEM { get; set; }
        public virtual SERVICE_PROPERTY_HEADER SERVICE_PROPERTY_HEADER { get; set; }
        public virtual SERVICE_PLAN SERVICE_PLAN { get; set; }
    }
}
