//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceHome.ServiceHomeDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class REALMESSAGE
    {
        public int MESSAGE_ID { get; set; }
        public string CONTENT { get; set; }
        public Nullable<bool> ISSUCESS { get; set; }
        public Nullable<int> RETRY_COUNT { get; set; }
        public Nullable<System.DateTime> CT { get; set; }
        public Nullable<bool> ISOUTDATE { get; set; }
    }
}
