//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceHome.ServiceHomeDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class REBACK_ITEM
    {
        public int REBACK_ITEM_ID { get; set; }
        public Nullable<int> RECHARGE_ID { get; set; }
        public Nullable<int> CITY_SERVICE_ID { get; set; }
        public Nullable<int> COUNT { get; set; }
        public int QUANTITY { get; set; }
    
        public virtual PROVINCE_BASIC_SERVICE PROVINCE_BASIC_SERVICE { get; set; }
        public virtual RECHARGE RECHARGE { get; set; }
    }
}
