//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceHome.ServiceHomeDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class RECHARGE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RECHARGE()
        {
            this.REBACK_ITEM = new HashSet<REBACK_ITEM>();
        }
    
        public int RECHARGE_ID { get; set; }
        public Nullable<int> MEM_PACK_ID { get; set; }
        public string RECHARGE_NAME { get; set; }
        public Nullable<int> RECHARGE_COUNT { get; set; }
        public Nullable<int> GIFT_COUNT { get; set; }
        public Nullable<bool> ISCASHGIFT { get; set; }
    
        public virtual MEMBERSHIP_PACKAGE MEMBERSHIP_PACKAGE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<REBACK_ITEM> REBACK_ITEM { get; set; }
    }
}
