//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceHome.ServiceHomeDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class SALRY
    {
        public int SALARY_ID { get; set; }
        public Nullable<int> STAFFID { get; set; }
        public Nullable<int> YEAR { get; set; }
        public Nullable<int> MONTH { get; set; }
        public Nullable<int> COMPLETE_ORDER_COUNT { get; set; }
        public Nullable<int> REJECT_ORDER_COUNT { get; set; }
        public Nullable<double> INCOME { get; set; }
        public Nullable<double> TARE { get; set; }
    
        public virtual STAFF STAFF { get; set; }
    }
}
