//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceHome.ServiceHomeDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class SELFSERVICE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SELFSERVICE()
        {
            this.EXTRA_DEMAND = new HashSet<EXTRA_DEMAND>();
        }
    
        public int SPECIAL_ID { get; set; }
        public Nullable<int> CITY_SERVICE_ID { get; set; }
        public string SELFSERVICE_NAME { get; set; }
        public Nullable<bool> ISOPEN { get; set; }
        public double COST { get; set; }
        public Nullable<bool> ISHOURCOST { get; set; }
        public Nullable<bool> ISAREACOST { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EXTRA_DEMAND> EXTRA_DEMAND { get; set; }
        public virtual PROVINCE_BASIC_SERVICE PROVINCE_BASIC_SERVICE { get; set; }
    }
}
