//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceHome.ServiceHomeDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class SELFSERVICE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SELFSERVICE()
        {
            this.ORDER_ITEM = new HashSet<ORDER_ITEM>();
        }
    
        public int SPECIAL_ID { get; set; }
        public Nullable<int> SERVICE_ID { get; set; }
        public string SELFSERVICE_NAME { get; set; }
        public Nullable<bool> ISOPEN { get; set; }
        public Nullable<decimal> UNIT_COST { get; set; }
        public string UNIT_NAME { get; set; }
        public Nullable<decimal> ONE_COST { get; set; }
        public string COST_TYPE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ORDER_ITEM> ORDER_ITEM { get; set; }
        public virtual SERVICE SERVICE { get; set; }
    }
}
