//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceHome.ServiceHomeDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class SERVICE_PLAN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SERVICE_PLAN()
        {
            this.RATE_PLAN = new HashSet<RATE_PLAN>();
        }
    
        public int SERVICE_PLAN_ID { get; set; }
        public Nullable<int> SERVICE_ID { get; set; }
        public string SERVICE_PLAN_NAME { get; set; }
        public string SERVICE_PLAN_DESC { get; set; }
        public string SERVICE_PLAN_URL { get; set; }
        public string SERVICE_LIMIT { get; set; }
        public string SERVICE_STANDARD { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RATE_PLAN> RATE_PLAN { get; set; }
    }
}
