//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceHome.ServiceHomeDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class SERVICE
    {
        public int SERVICE_ID { get; set; }
        public string SERVICE_CODE { get; set; }
        public string SERVICE_NAME { get; set; }
        public Nullable<System.DateTime> CREATE_TIME { get; set; }
        public string URL { get; set; }
        public Nullable<bool> ISLEAF { get; set; }
        public string PICURL { get; set; }
        public string SERVICE_ITEMS { get; set; }
        public Nullable<int> PARENT_SERVICE_ID { get; set; }
    }
}
