//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceHome.ServiceHomeDB
{
    using System;
    using System.Collections.Generic;

    public partial class SERVICEPLACES
    {
        public int SERVICE_PLACE_ID { get; set; }
        public int USERID { get; set; }
        public string PLACE_DETAIL { get; set; }
        public string PHONE { get; set; }
        public System.DateTime LAST_TIME { get; set; }
        public System.DateTime CREATE_TIME { get; set; }
        public string ADDR_TITLE { get; set; }
    }
}
