//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceHome.ServiceHomeDB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class housekeepingEntities : DbContext
    {
        public housekeepingEntities()
            : base("name=housekeepingEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AUTHORMODULES> AUTHORMODULES { get; set; }
        public virtual DbSet<CASH_LOG> CASH_LOG { get; set; }
        public virtual DbSet<CHECKCODERECORD> CHECKCODERECORD { get; set; }
        public virtual DbSet<CITY> CITY { get; set; }
        public virtual DbSet<COMMISION_RULE> COMMISION_RULE { get; set; }
        public virtual DbSet<COMMISION_RULE_ITEM> COMMISION_RULE_ITEM { get; set; }
        public virtual DbSet<COMPANY_CHILD> COMPANY_CHILD { get; set; }
        public virtual DbSet<COMPANY_DETAIL_ITEM> COMPANY_DETAIL_ITEM { get; set; }
        public virtual DbSet<COUPON_INFO> COUPON_INFO { get; set; }
        public virtual DbSet<COUPON_RECORD> COUPON_RECORD { get; set; }
        public virtual DbSet<DETAIL_ITEM> DETAIL_ITEM { get; set; }
        public virtual DbSet<EXTRA_DEMAND> EXTRA_DEMAND { get; set; }
        public virtual DbSet<FEEDBACK> FEEDBACK { get; set; }
        public virtual DbSet<MASTERS> MASTERS { get; set; }
        public virtual DbSet<MEMBERSHIP_PACKAGE> MEMBERSHIP_PACKAGE { get; set; }
        public virtual DbSet<MODULES> MODULES { get; set; }
        public virtual DbSet<OPERATION_LOG> OPERATION_LOG { get; set; }
        public virtual DbSet<ORDER_ITEM> ORDER_ITEM { get; set; }
        public virtual DbSet<ORDERS> ORDERS { get; set; }
        public virtual DbSet<PACK_TYPE> PACK_TYPE { get; set; }
        public virtual DbSet<PROVICE> PROVICE { get; set; }
        public virtual DbSet<PROVINCE_BASIC_SERVICE> PROVINCE_BASIC_SERVICE { get; set; }
        public virtual DbSet<RATEPLAN> RATEPLAN { get; set; }
        public virtual DbSet<REALMESSAGE> REALMESSAGE { get; set; }
        public virtual DbSet<REBACK_ITEM> REBACK_ITEM { get; set; }
        public virtual DbSet<RECHARGE> RECHARGE { get; set; }
        public virtual DbSet<SALRY> SALRY { get; set; }
        public virtual DbSet<SELFSERVICE> SELFSERVICE { get; set; }
        public virtual DbSet<SERVICE_ITEM> SERVICE_ITEM { get; set; }
        public virtual DbSet<STAFF> STAFF { get; set; }
        public virtual DbSet<STAFF_LEVEL> STAFF_LEVEL { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<USER> USER { get; set; }
        public virtual DbSet<USER_LEVEL> USER_LEVEL { get; set; }
        public virtual DbSet<WORKOFF> WORKOFF { get; set; }
    }
}
