//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceHome.ServiceHomeDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class SERVICE_ITEM
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SERVICE_ITEM()
        {
            this.COMMISION_RULE_ITEM = new HashSet<COMMISION_RULE_ITEM>();
            this.PROVINCE_BASIC_SERVICE = new HashSet<PROVINCE_BASIC_SERVICE>();
            this.SERVICE_ITEM1 = new HashSet<SERVICE_ITEM>();
        }
    
        public int SERVICE_ID { get; set; }
        public Nullable<int> PARENT_SERVICE_ID { get; set; }
        public byte[] SERVICE_ITEM_NAME { get; set; }
        public byte[] SERVICECONTENT { get; set; }
        public Nullable<System.DateTime> CT { get; set; }
        public string URL { get; set; }
        public Nullable<bool> ISLEAF { get; set; }
        public string PICURL { get; set; }
        public Nullable<int> LEAF_DEPT { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<COMMISION_RULE_ITEM> COMMISION_RULE_ITEM { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PROVINCE_BASIC_SERVICE> PROVINCE_BASIC_SERVICE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SERVICE_ITEM> SERVICE_ITEM1 { get; set; }
        public virtual SERVICE_ITEM SERVICE_ITEM2 { get; set; }
    }
}
