//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceHome.ServiceHomeDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class USERS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public USERS()
        {
            this.COUPON_RECORD = new HashSet<COUPON_RECORD>();
            this.ORDERS = new HashSet<ORDERS>();
            this.SERVICEPLACES = new HashSet<SERVICEPLACES>();
        }
    
        public int USERID { get; set; }
        public string USERNAME { get; set; }
        public string PASSWORD { get; set; }
        public string ADDR { get; set; }
        public string EMAIL { get; set; }
        public string PHONE { get; set; }
        public Nullable<System.DateTime> CT { get; set; }
        public Nullable<System.DateTime> LASTUPDATETIME { get; set; }
        public string IDCARD { get; set; }
        public string QQ { get; set; }
        public Nullable<int> STATE { get; set; }
        public string LASTIP { get; set; }
        public Nullable<System.DateTime> LASTACTION { get; set; }
        public Nullable<int> USER_LEVEL { get; set; }
        public Nullable<double> CASH_ALL { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<COUPON_RECORD> COUPON_RECORD { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ORDERS> ORDERS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SERVICEPLACES> SERVICEPLACES { get; set; }
        public virtual USER_LEVEL USER_LEVEL1 { get; set; }
        public virtual USER_LEVEL USER_LEVEL2 { get; set; }
    }
}
